apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-success
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: deploy-success
        image: curlimages/curl
        command:
            - curl
            - |
              --location --request PUT 'https://googl.com/metrics?appName=sdsdsend&metricType=sdsdsds' \
              --header 'Content-Type: application/json' \
              --header 'X-YOSI: sdssdsdsd' \
                --data-raw '{
              "owner": "ilya",
              "gitHash": "sdsdsds",
              "uniqueId": "666",
              "branch": "master",
              "elapsed": 1,
              "status": "success",
              "region": "us-east-1",
              }'
      restartPolicy: Never
  backoffLimit: 2
