apiVersion: argoproj.io/v1alpha1               # Create a rollout resource
kind: Rollout
metadata:
  name: guest-reoll-dep
spec:
  replicas: 3
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: guestbook-ui-deployment
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 1

