apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook
  annotations:
    notifications.argoproj.io/subscribe.on-analysis-run-error.slack: general
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: general
    notifications.argoproj.io/subscribe.analysis-run-failed.slack: general 
    notifications.argoproj.io/subscribe.analysis-run-running.slack: general 
    
spec:
  replicas: 7
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
          name: guestbook-ui
          ports:
            - containerPort: 80
  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 1 # delay starting analysis run until setWeight: 40%
      steps:
      - setWeight: 20
      - pause: {duration: 1s}
#       - analysis:
#           templates:
#           - templateName: success-rate
#           dryRun:
#           - metricName: success-rate
      - setWeight: 40
      - pause: {duration: 1s}
      - setWeight: 60
      - pause: {duration: 1s}
      - setWeight: 80
      - pause: {duration: 1s}
