apiVersion: batch/v1
kind: Job
metadata:
  name: pre-status
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "sleep 30" ]
      restartPolicy: Never
  backoffLimit: 0
