apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-deployment

spec:
  replicas: 0
  selector:
    matchLabels:
      app: guestbook-ui-deployment
  template:
    metadata:
      labels:
        app: guestbook-ui-deployment
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: guestbook-ui
          ports:
            - containerPort: 80

