apiVersion: batch/v1
kind: Job
metadata:
  name: pre-status
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: pre-status
          image: curlimages/curl
          command: ["sleep 10"]
      restartPolicy: Never
  backoffLimit: 0
