apiVersion: batch/v1
kind: Job
metadata:
  generateName: deploy-success-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: deploy-success
        image: curlimages/curl
        command:
          - "curl"
          - "https://google.com"
      restartPolicy: Never
  backoffLimit: 2
