apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-for-notification
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: general
    notifications.argoproj.io/subscribe.rollout-step-completed.slack: general
  labels:
    argocd.argoproj.io/instance: stage-use1-monday-sdsdds-sdsd-platform
 
    
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
          name: guestbook-ui
          ports:
            - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 1s}
      - setWeight: 40
      - pause: {duration: 10s}
      - setWeight: 60
      - pause: {duration: 1s}
      - setWeight: 80
      - pause: {duration: 1s}
